### ISSUE TITLE
Variables of type float are rounded

### ISSUE THREAD

**Issue by meckhardt** [theserverlessway/formica#122]
I used in my stack configuration file floating numbers:

```
vars:
  DatabaseEngineVersion: 10.5
```

However when these variable is applied via `formica diff` I receive `10.500` as a value which in this case leads to an error when creating a database with this concrete version (e.g. aurora). 

However if I use `formica template` it seems to show the correct value `10.5`.

Here how it looks like when `formica diff` is used.

![image](https://user-images.githubusercontent.com/827666/54220750-65128e00-44f2-11e9-898f-11220419fd72.png)

**Comment by flomotlik** [comment]
this should have already been resolved in an earlier version. Please reopen if it isn't
