### ISSUE TITLE
Support for "region only" organization variables

### ISSUE THREAD

**Issue by besbes** [theserverlessway/formica#147]
The option `organization_variables` enables the inclusion of AWS accounts and regions as template variables (`AWSRegions`, `AWSAccounts`, etc.). In an environment where deployment into sub-accounts is not possible or not desired, there is no way to retrieve *only* the AWS regions and use them in a template. 

Proposed solution:
* Add new options `organization_region_variables` and `organization_account_variables ` which provide regions and accounts, respectively.
* Option `organization_variables` remains as combination of `organization_region_variables` and `organization_account_variables`

**Comment by flomotlik** [comment]
thanks for the PR
