### ISSUE TITLE
Enable server-side encryption for S3 buckets

### ISSUE THREAD

**Issue by besbes** [theserverlessway/formica#172]
When using a S3 bucket to upload CloudFormation templates, a temporary S3 bucket may be created. Due to policies it may be required to apply server-side encryption to this bucket. Even if it's just a temporary one, it may remain in place (e.g. if the deployment process is interrupted before the bucket is deleted).

**Comment by flomotlik** [comment]
Yup totally makes sense. The PR would need some test though, should be easy to extend the current one. Let me know if there are questions
