### ISSUE TITLE
Persist "session" across multiple formica invocations.

### ISSUE THREAD

**Issue by muja** [theserverlessway/formica#87]
Every time `formica` is invoked, MFA is necessary, no matter how far apart those invocations are. I don't know how `aws-cli` does it so you can use it many minutes after authenticating... maybe you know more? It would definitely be useful!

**Comment by flomotlik** [comment]
Yup this is a PITA with MFA. I'm currently using [`awsinfo assume role`](https://github.com/flomotlik/awsinfo/blob/master/scripts/commands/assume/role.md) to get credentials and export them into the environment.

What AWSCLI does is it stores the credentials that are created through `aws sts` in the `~/.aws` folder and once they run out asks you for new ones.

I'm definitely very open to getting this into Formica, but I don't have the time at the moment to implement this myself (and the workaround through `awsinfo assume` is OKish enough for me for now). But if someone wants to contribute I'd be open to help and get this in.

**Comment by flomotlik** [comment]
@muja this has been fixed recently and its being cached
